// Code generated by internal/generate/sweepimp/main.go; DO NOT EDIT.

package sweep_test

import (
	"context"
	"testing"

	"github.com/cloudbuzzbyone/terraform-provider-appflow/internal/sweep"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestMain(m *testing.M) {
	sweep.ServicePackages = servicePackages(context.Background())
	resource.TestMain(m)
}
