// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/service/appflow"
	"golang.org/x/exp/slices"
)

func servicePackages(ctx context.Context) []conns.ServicePackage {
	v := []conns.ServicePackage{
		appflow.ServicePackage(ctx),
	}

	return slices.Clone(v)
}
